namespace: betalodger
port: 80
targetport: 80

application:
  name: nginx-betalodger-deployment
  app: nginx-betalodger
  image: "registry.gitlab.com/arthurg35500/lodger-vitrine-frontend"
  version: "__VERSION__"
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "0.5"
    memory: "512Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

readinessProbe:
  path: /
  port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  name: nginx-betalodger-autoscaler
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemory: 512Mi
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 25
          periodSeconds: 30

service:
  name: nginx-betalodger-service
  type: LoadBalancer
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "0.5"
    memory: "512Mi"

nodeSelector: {}

tolerations: []

affinity: {}
